# Generated by Django 4.2 on 2023-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
